{
  "formatVersion": "1.1",
  "component": {
    "group": "org.maplibre.gl",
    "module": "android-sdk-geojson",
    "version": "6.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-geojson-6.0.1.jar",
          "url": "android-sdk-geojson-6.0.1.jar",
          "size": 70349,
          "sha512": "19d485468a4139ea9a16908ac39aa272d1ae0af95d2dd0caefb4a78c9f12e37e71080d239102a073a7147b0fe347be774c104cb56d7d218be14ba3239c1e4366",
          "sha256": "0c4e4258ce258da9740c17c76f3ae90f89fcfa5822a797f5d466b35410571363",
          "sha1": "256e046d9f5756f2ce2e70110741b025bf3080f0",
          "md5": "2f9e454c5d75b52792671ebf56cf2b9e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 7,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "android-sdk-geojson-6.0.1.jar",
          "url": "android-sdk-geojson-6.0.1.jar",
          "size": 70349,
          "sha512": "19d485468a4139ea9a16908ac39aa272d1ae0af95d2dd0caefb4a78c9f12e37e71080d239102a073a7147b0fe347be774c104cb56d7d218be14ba3239c1e4366",
          "sha256": "0c4e4258ce258da9740c17c76f3ae90f89fcfa5822a797f5d466b35410571363",
          "sha1": "256e046d9f5756f2ce2e70110741b025bf3080f0",
          "md5": "2f9e454c5d75b52792671ebf56cf2b9e"
        }
      ]
    }
  ]
}
