package com.ali.fluttertemplate

import android.content.res.AssetManager
import android.util.Log
import com.itsaky.androidide.plugins.IPlugin
import com.itsaky.androidide.plugins.PluginContext
import com.itsaky.androidide.plugins.services.IdeFileService
import com.itsaky.androidide.plugins.services.IdeTemplateService
import java.io.File

/**
 * Headless installer plugin. On [activate] it registers five Flutter starter
 * templates with the IDE so they appear on the New Project screen alongside the
 * built-in core templates; on [deactivate] it unregisters them and deletes the
 * staged `.cgt` files.
 *
 * Each template is authored as a Pebble skeleton bundled under
 * `assets/templates/<Variant>/`. The template metadata (name, description,
 * package-name option, parameters) is generated by [IdeTemplateService]'s
 * builder — the bundled `template/` folder only supplies the thumbnail.
 *
 * This replaces the original submission's approach of writing hardcoded Dart
 * files to external storage, which fails under scoped storage on modern devices.
 */
class FlutterTemplate : IPlugin {

    private lateinit var context: PluginContext
    private var templateService: IdeTemplateService? = null
    private var fileService: IdeFileService? = null

    /** Registered template name -> staged .cgt file, for cleanup on deactivate. */
    private val registered = mutableMapOf<String, File>()

    override fun initialize(context: PluginContext): Boolean {
        return try {
            this.context = context
            templateService = context.services.get(IdeTemplateService::class.java) ?: return false
            fileService = context.services.get(IdeFileService::class.java) ?: return false
            context.logger.info("FlutterTemplate initialized successfully")
            true
        } catch (e: Exception) {
            context.logger.error("FlutterTemplate initialization failed", e)
            false
        }
    }

    override fun activate(): Boolean {
        for (variant in VARIANTS) {
            registerTemplate(variant)?.let { registered[variant.name] = it }
        }
        context.logger.info("FlutterTemplate: registered ${registered.size}/${VARIANTS.size} templates")
        return true
    }

    override fun deactivate(): Boolean {
        val ts = templateService
        for ((name, file) in registered) {
            runCatching {
                val unregistered = ts?.unregisterTemplate(name) ?: false
                context.logger.info("$name unregistered: $unregistered")
                if (file.exists()) {
                    val deleted = fileService?.delete(file) ?: false
                    context.logger.info("$name staged file removed: $deleted")
                }
            }.onFailure { context.logger.error("FlutterTemplate: cleanup failed for $name", it) }
        }
        registered.clear()
        return true
    }

    override fun dispose() {
        templateService = null
        fileService = null
        registered.clear()
        context.logger.info("FlutterTemplate: Disposing plugin")
    }

    private fun registerTemplate(variant: Variant): File? {
        val assetRoot = "templates/${variant.assetDir}"
        return runCatching {
            var builder = templateService!!.createTemplateBuilder(variant.name)
                .description(variant.description)
                .showPackageNameOption()
                .thumbnailFromAssets("$assetRoot/template/thumb.png", context)

            for (assetFile in listBundledAssetFiles(assetRoot)) {
                if (assetFile.startsWith("template/")) continue
                builder = builder.addStaticFromAssets(assetFile, "$assetRoot/$assetFile", context)
            }

            val cgtFile = builder.build(context.resources.getPluginDirectory())
            templateService!!.registerTemplate(cgtFile)
            Log.i(TAG, "${variant.name} template registered")
            cgtFile
        }.onFailure {
            Log.e(TAG, "Failed to register ${variant.name} template", it)
        }.getOrNull()
    }

    private fun listBundledAssetFiles(rootAssetPath: String): List<String> {
        val results = mutableListOf<String>()
        walkAssets(context.androidContext.assets, rootAssetPath, "", results)
        return results
    }

    private fun walkAssets(assets: AssetManager, rootPath: String, relativePath: String, out: MutableList<String>) {
        val absolute = if (relativePath.isEmpty()) rootPath else "$rootPath/$relativePath"
        val children = assets.list(absolute) ?: return
        if (children.isEmpty()) {
            out.add(relativePath)
            return
        }
        for (child in children) {
            val nextRelative = if (relativePath.isEmpty()) child else "$relativePath/$child"
            walkAssets(assets, rootPath, nextRelative, out)
        }
    }

    private data class Variant(val name: String, val assetDir: String, val description: String)

    private companion object {
        const val TAG = "FlutterTemplate"

        val VARIANTS = listOf(
            Variant("Flutter Basic", "FlutterBasic",
                "A minimal Flutter starter app with a counter screen"),
            Variant("Flutter BLoC", "FlutterBloc",
                "A Flutter app wired with the BLoC state-management pattern"),
            Variant("Flutter Provider", "FlutterProvider",
                "A Flutter app wired with the Provider state-management pattern"),
            Variant("Flutter GetX", "FlutterGetx",
                "A Flutter app wired with the GetX state-management pattern"),
            Variant("Flutter Riverpod", "FlutterRiverpod",
                "A Flutter app wired with the Riverpod state-management pattern"),
        )
    }
}
